const API_BASE='https://api-loteria.pabloclementeperez.com/output/';
const API={navidad:{numbers:`${API_BASE}LoteriaNavidad.json`,summary:`${API_BASE}LoteriaNavidadResumen.json`,status:`${API_BASE}LoteriaNavidadStatus.json`},nino:{numbers:`${API_BASE}LoteriaElNino.json`,summary:`${API_BASE}LoteriaElNinoResumen.json`,status:`${API_BASE}LoteriaElNinoStatus.json`}};
const PRIZES={navidad:['Premio Gordo','Segundo Premio','Tercer Premio','Primer Cuarto','Segundo Cuarto','Primer Quinto','Segundo Quinto','Tercer Quinto','Cuarto Quinto','Quinto Quinto','Sexto Quinto','Séptimo Quinto','Octavo Quinto'],nino:['Primer premio','Segundo Premio','Tercer Premio','Extracción 4 cifras 1','Extracción 4 cifras 2','Extracción 3 cifras 1','Extracción 3 cifras 2','Extracción 3 cifras 3','Extracción 3 cifras 4','Extracción 3 cifras 5','Extracción 3 cifras 6','Extracción 3 cifras 7','Extracción 3 cifras 8','Extracción 3 cifras 9','Extracción 3 cifras 10','Extracción 3 cifras 11','Extracción 3 cifras 12','Extracción 3 cifras 13','Extracción 3 cifras 14','Extracción 2 cifras 1','Extracción 2 cifras 2','Extracción 2 cifras 3','Extracción 2 cifras 4','Extracción 2 cifras 5','Reintegro 1','Reintegro 2','Reintegro 3']};
const NINO_KEYS=['Primer_premio','Segundo_Premio','Tercer_Premio','Extraccion_4_cifras_1','Extraccion_4_cifras_2',...Array.from({length:14},(_,i)=>`Extraccion_3_cifras_${i+1}`),...Array.from({length:5},(_,i)=>`Extraccion_2_cifras_${i+1}`),...Array.from({length:3},(_,i)=>`Reintegro_${i+1}`)];
let state={lottery:'navidad',tab:'buscar',numbers:{navidad:{},nino:{}},summary:{navidad:null,nino:null},status:{navidad:null,nino:null},saved:{navidad:[],nino:[]}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
document.addEventListener('DOMContentLoaded',()=>{loadSaved();bind();initAnalytics();initAds();loadData();renderAll()});
function bind(){
  $$('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
  $('.brand').addEventListener('click',e=>{e.preventDefault();switchTab('buscar')});
  $$('[data-lottery]').forEach(b=>b.addEventListener('click',()=>switchLottery(b.dataset.lottery)));
  $('#searchForm').addEventListener('submit',e=>{e.preventDefault();checkAndSave()});
  $('#numberInput').addEventListener('input',e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,5)});
  $('#refreshHistoryBtn').addEventListener('click',()=>loadData()); $('#refreshSummaryBtn').addEventListener('click',()=>loadData()); $('#checkStatusBtn').addEventListener('click',()=>loadData(true)); $('#deleteAllBtn').addEventListener('click',deleteAll); $('#shareBtn').addEventListener('click',share);
  $('#modalClose').addEventListener('click',closeModal); $('#modalOk').addEventListener('click',closeModal); $('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()}); document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modal').hidden)closeModal()}); $('#otherAppsBtn').addEventListener('click',()=>window.open('https://pabloclementeperez.com','_blank'));
  $$('.contact-btn').forEach(b=>b.addEventListener('click',()=>contact(b.dataset.contact)));
}
function initAnalytics(){const logPageView=()=>track('page_view',{page_title:document.title});if(window.loteriaAnalytics)logPageView();else window.addEventListener('firebase-ready',logPageView,{once:true})}
function track(name,params={}){try{window.loteriaAnalytics?.logEvent(name,params)}catch(e){}}
function initAds(){const id=window.LOTERIA_AD_CONFIG?.publisherId;if(!id)return;const script=document.createElement('script');script.src='https://media.ethicalads.io/media/client/ethicalads.min.js';script.async=true;document.head.appendChild(script);$$('.ad-slot').forEach(slot=>{slot.innerHTML='';slot.dataset.eaPublisher=id;slot.dataset.eaType='image';slot.classList.add('ethicalads')})}
function loadSaved(){['navidad','nino'].forEach(l=>{try{state.saved[l]=JSON.parse(localStorage.getItem(`loteria_saved_${l}`)||'[]')}catch{state.saved[l]=[]}});updateCount()}
function save(){localStorage.setItem(`loteria_saved_${state.lottery}`,JSON.stringify(state.saved[state.lottery]));updateCount()}
function updateCount(){$('#savedCount').textContent=state.saved.navidad.length+state.saved.nino.length}
function switchTab(tab){state.tab=tab;$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`panel-${tab}`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));track('select_content',{content_type:'tab',item_id:tab});renderAll()}
function switchLottery(lottery){state.lottery=lottery;$$('[data-lottery]').forEach(b=>b.classList.toggle('active',b.dataset.lottery===lottery));track('select_content',{content_type:'lottery',item_id:lottery});loadData();renderAll()}
async function fetchJSON(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
async function loadData(show=false){if(show)toast('Actualizando datos…');const l=state.lottery;try{const [numbers,summary,status]=await Promise.all([fetchJSON(API[l].numbers),fetchJSON(API[l].summary),fetchJSON(API[l].status)]);state.numbers[l]=numbers||{};state.summary[l]=summary||{};state.status[l]=status||{};renderAll();$('#lastUpdateInfo')?.remove();if(show)toast('Datos actualizados')}catch(e){console.warn(e);if(!state.status[l])toast('No se pudo conectar con el servidor. Tus números siguen guardados.');renderAll()}}
function normalNumber(value){return String(parseInt(value,10)||0).padStart(5,'0')}
function prizeFor(number){const key=normalNumber(number),record=state.numbers[state.lottery]?.[key];if(record==null)return null;const raw=typeof record==='object'?(record.premio??record.quantity??record.prize):record;const amount=Number(String(raw).replace(',','.'));return {amount:Number.isFinite(amount)?Math.floor(amount/10):0,description:typeof record==='object'?(record.descripcion||record.description||''):''}}
function resultFor(number){const status=Number(state.status[state.lottery]?.status);const prize=prizeFor(number);if(status===0)return{type:'info',title:'Sorteo no comenzado',message:'El número se ha guardado para que puedas consultarlo cuando empiece el sorteo.'};if(prize)return{type:'winner',title:'¡Premiado!',message:`Premio al décimo: ${prize.amount.toLocaleString('es-ES')} €`,prize};if(status===1)return{type:'pending',title:'Aún no ha salido',message:'El sorteo está en curso. Podría aparecer más adelante.'};return{type:'none',title:'Sin premio',message:'Este número no figura entre los premios publicados.'}}
function checkAndSave(){const raw=$('#numberInput').value.trim();if(!raw)return showModal('Número incorrecto','Introduce un número entre 0 y 99.999.','error');const n=Number(raw);if(!Number.isInteger(n)||n<0||n>99999)return showModal('Número incorrecto','El número debe estar entre 0 y 99.999.','error');const number=normalNumber(n),exists=state.saved[state.lottery].some(x=>x.number===number);if(!exists){state.saved[state.lottery].unshift({id:crypto.randomUUID?.()||String(Date.now()),number,quantity:Number($('#quantityInput').value)||20,comment:$('#commentInput').value.trim()});save()}track('search_number',{lottery:state.lottery,number});const result=resultFor(number);$('#numberInput').value='';$('#commentInput').value='';renderAll();showResult(number,result);}
function showResult(number,r){$('#searchResult').innerHTML=`<div class="result-card ${r.type==='winner'?'winner':''}"><p class="eyebrow">${r.type==='winner'?'Resultado':'Consulta guardada'}</p><h3>${r.title} · ${number}</h3><p>${r.message}${r.prize?.description?` · ${escapeHTML(r.prize.description)}`:''}</p></div>`;showModal(r.title,`El número ${number}. ${r.message}`,r.type==='winner'?'success':'info')}
function renderAll(){renderHistory();renderSummary();renderStatus()}
function renderHistory(){const c=$('#myNumbersList'),items=state.saved[state.lottery];if(!items.length){c.innerHTML='<div class="empty-state">Aún no tienes números guardados para este sorteo.<br>Comprueba uno y aparecerá aquí.</div>';return}c.innerHTML=items.map(x=>{const r=resultFor(x.number),p=r.prize,qty=Number(x.quantity)||20;const received=p?Math.round(p.amount*qty/20):0;return`<article class="number-item ${p?'has-prize':''}"><div><div class="number-main">${x.number}</div><div class="number-meta">${qty} € jugados${x.comment?` · ${escapeHTML(x.comment)}`:''}</div>${p?`<div class="number-prize">✦ Premio estimado: ${received.toLocaleString('es-ES')} €</div>`:''}</div><button class="delete-number" data-delete="${x.id}" aria-label="Borrar ${x.number}">×</button></article>`}).join('');$$('[data-delete]').forEach(b=>b.addEventListener('click',()=>{state.saved[state.lottery]=state.saved[state.lottery].filter(x=>String(x.id)!==String(b.dataset.delete));save();renderHistory();toast('Número eliminado')}))}
function extractPrizes(){const data=state.summary[state.lottery]||{},keys=state.lottery==='nino'?NINO_KEYS:Array.from({length:13},(_,i)=>`numero${i+1}`);return keys.map((k,i)=>{const v=data[k];return v===undefined||v===null?null:{label:PRIZES[state.lottery][i],number:Number(v)===-1?'Pendiente':(Number(v)===0?'—':normalNumber(v))}}).filter(Boolean)}
function renderSummary(){const c=$('#summaryList'),items=extractPrizes();c.innerHTML=items.length?items.map((x,i)=>`<article class="summary-item ${i<3?'major':''}"><span class="prize-name">${x.label}</span><strong class="prize-value">${x.number}</strong></article>`).join(''):'<div class="empty-state">Los premios aparecerán cuando el servidor publique el resumen.</div>'}
function renderStatus(){const s=Number(state.status[state.lottery]?.status),title=$('#statusTitle'),msg=$('#statusMessage'),dot=$('#statusDot');if(!state.status[state.lottery]){title.textContent='Sin conexión';msg.textContent='No se pudo consultar el estado. Puedes reintentarlo.';dot.className='status-dot';return}if(s===0){title.textContent='Todavía no ha empezado';msg.textContent='El número se queda guardado y podrás comprobarlo después.';dot.className='status-dot'}else if(s===1){title.textContent='Sorteo en curso';msg.textContent='La lista se está actualizando. Vuelve a consultar en unos minutos.';dot.className='status-dot live'}else{title.textContent='Sorteo finalizado';msg.textContent='La lista publicada corresponde al sorteo terminado.';dot.className='status-dot done'}}
function deleteAll(){if(!state.saved[state.lottery].length)return;if(confirm('¿Borrar todos tus números de este sorteo?')){state.saved[state.lottery]=[];save();renderHistory();toast('Histórico borrado')}}
function share(){const data={title:'Lotería · Comprueba tu suerte',text:'Comprueba tus números de la Lotería de Navidad y El Niño',url:location.href};if(navigator.share)navigator.share(data).catch(()=>{});else navigator.clipboard?.writeText(location.href).then(()=>toast('Enlace copiado'))}
function contact(person){const contacts={pablo:{name:'Pablo Clemente Pérez',links:[['✉','Email','pabloclemente08@gmail.com','mailto:pabloclemente08@gmail.com?subject=Lotería%20Navidad'],['in','LinkedIn','Perfil profesional','https://es.linkedin.com/in/pabloclementeperez'],['𝕏','X / Twitter','@pclemnte','https://x.com/pclemnte'],['↗','Página web','pabloclementeperez.wordpress.com','https://pabloclementeperez.wordpress.com/']]},elena:{name:'Elena Gordaliza Fdez',links:[['✉','Email','ele.aliza@gmail.com','mailto:ele.aliza@gmail.com?subject=Lotería%20Navidad'],['in','LinkedIn','Perfil profesional','https://www.linkedin.com/in/elena-gordaliza-18163a63/'],['𝕏','X / Twitter','@Elealiza','https://x.com/Elealiza']]}}[person];if(!contacts)return;$('#modal').classList.add('contact-mode');$('#modalIcon').textContent='♡';$('#modalTitle').textContent=`Contactar con ${contacts.name}`;$('#modalMessage').textContent='Elige cómo quieres ponerte en contacto.';$('#contactOptions').innerHTML=contacts.links.map(([glyph,label,detail,url])=>`<a class="contact-option" href="${url}" target="_blank" rel="noreferrer"><span class="contact-glyph">${glyph}</span><span>${label}<small>${detail}</small></span></a>`).join('');$('#contactOptions').hidden=false;$('#modal').hidden=false;track('select_content',{content_type:'contact',item_id:person})}
function escapeHTML(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function showModal(title,message,type){$('#modal').classList.remove('contact-mode');$('#contactOptions').hidden=true;$('#modalTitle').textContent=title;$('#modalMessage').textContent=message;$('#modalIcon').textContent=type==='success'?'✦':type==='error'?'!':'i';$('#modal').hidden=false}function closeModal(){$('#modal').classList.remove('contact-mode');$('#contactOptions').hidden=true;$('#modal').hidden=true}
